Create dummy key using crypto iso parsing invalid key.
node-opcua/node-opcua pull request #1239
Opened 2023-02-07 10:26 UTC by ptillemans

Fixes #1238

Since `invalidPrivateKey` is AFAICT  essentially only used to have a value of the right type and to detect that the private key has not been set by the API user, a random private key can suffice as there is an insignificant chance there will ever be a collision. Also creating a private key from value 0 is a bug magnet as was demonstrated by the Java TLS implementation quite recently.

By creating a key, the key will be created by the same library which will be using it, so the likelihood of subtle conflicts between BoringSSL and OpenSSL becomes much more remote.

2023-02-07 10:26 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/node-opcua/node-opcua?pullRequest=1239) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/node-opcua/node-opcua?pullRequest=1239) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/node-opcua/node-opcua?pullRequest=1239) it.</sub>

2023-02-17 10:20 UTC, EirikVea requested changes

2023-02-17 10:20 UTC, EirikVea commented on packages/node-opcua-secure-channel/source/message_builder.ts
> +export const { invalidPrivateKey, _} = generateKeyPairSync('rsa', {
This should be `export const { privateKey: invalidPrivateKey } = ...`

2023-02-17 14:36 UTC, EirikVea requested changes
Actually, looks like won't work either (or at least it won't compile). After studying the documentation for [generateKeyPairSync](https://nodejs.org/api/crypto.html#cryptogeneratekeypairsynctype-options) I see that if `publicKeyEncoding` or `privateKeyEncoding` is supplied, a pair of strings will be returned. If you just remove the encoding options you will get a pair of `KeyObject`s returned, which is in turn what the `PrivateKey` type is an alias for, as far as I can tell.

2023-02-21 09:27 UTC, EirikVea commented
> You are right again. I now spent some time to figure out how to run the tests locally on my PC.
> 
> Typefluidity in the Javascript/Typescript ecosystem is disturbing.
> 
> I updated a fixed version. I must say that it does become more elegant over time...

Yeah, I cloned your repo myself and checked that what I suggested actually compiled upfront this time 😆 
I agree with your observations on type fluidity. At least with TypeScript we have a fighting chance of detecting these sorts of things at compile time 🤯 

Anyway, nice work!

2023-02-24 12:58 UTC, ptillemans commented
No idea why the coverage fails.

```
/home/runner/work/node-opcua/node-opcua/node_modules/.pnpm/coveralls@3.1.1/node_modules/coveralls/bin/coveralls.js:19
      throw err;
      ^
Bad response: 422 {"message":"Couldn't find a repository matching this job.","error":true}
(Use `node --trace-uncaught ...` to show where the exception was thrown)
make: *** [Makefile:16: coveralls] Error 1
Error: Process completed with exit code 2.
```

I have no idea how this relates to the changes in message_builder.ts.

2023-02-24 13:00 UTC, AndreasHeine commented
> No idea why the coverage fails.
> 
> ```
> /home/runner/work/node-opcua/node-opcua/node_modules/.pnpm/coveralls@3.1.1/node_modules/coveralls/bin/coveralls.js:19
>       throw err;
>       ^
> Bad response: 422 {"message":"Couldn't find a repository matching this job.","error":true}
> (Use `node --trace-uncaught ...` to show where the exception was thrown)
> make: *** [Makefile:16: coveralls] Error 1
> Error: Process completed with exit code 2.
> ```
> 
> I have no idea how this relates to the changes in message_builder.ts. 

you need rights for that!

2023-02-27 12:45 UTC, ptillemans commented
I rebased to current master.

2023-03-01 20:05 UTC, erossignon commented
Fixed in commit 526843c6a26b6e3d0036e53a0f227c128daa625b by simply hardcoding a valid random private key.

2023-03-01 20:05 UTC, closed without merging

2023-03-01 20:06 UTC, erossignon commented
Fixed in commit 526843c6a26b6e3d0036e53a0f227c128daa625b by simply hardcoding a valid random private key.