Emit "newAlarm" when alarm is undefined
node-opcua/node-opcua pull request #928
Opened 2021-01-10 22:17 UTC by maneetgoyal

- Fixes https://github.com/node-opcua/node-opcua/issues/793

2021-01-10 23:20 UTC, maneetgoyal commented
@erossignon Can you please suggest how to fix the CI failure?

2021-01-11 20:39 UTC, erossignon commented
The CI failure : in fact the test passes .. only publishing coverage report to coveralls website fails...

2021-01-15 01:34 UTC, maneetgoyal commented
> The CI failure : in fact the test passes .. only publishing coverage report to coveralls website fails...

It might be this issue: https://github.com/lemurheavy/coveralls-public/issues/632. Will give it another go.

2021-04-05 18:34 UTC, erossignon requested changes
Please add a unit test

2021-04-05 18:34 UTC, erossignon commented on packages/node-opcua-client/source/alarms_and_conditions/client_alarm_list.ts
> +            this.emit("newAlarm", newAlarm);
A unit test is requested

2021-05-21 00:53 UTC, maneetgoyal commented on packages/node-opcua-client/source/alarms_and_conditions/client_alarm_list.ts
> +            this.emit("newAlarm", newAlarm);
On it 👍

2021-05-21 01:28 UTC, maneetgoyal commented on packages/node-opcua-client/source/alarms_and_conditions/client_alarm_list.ts
> +            this.emit("newAlarm", newAlarm);
Done, please check.

2021-08-20 09:03 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/node-opcua/node-opcua?pullRequest=928) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/node-opcua/node-opcua?pullRequest=928) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/node-opcua/node-opcua?pullRequest=928) it.</sub>

2021-10-04 04:29 UTC, closed without merging