Add support for boolean data in coerceVariantType
node-opcua/node-opcua pull request #929
Opened 2021-01-10 23:19 UTC by maneetgoyal

Fixes #794

2021-04-05 18:36 UTC, erossignon requested changes
Please add a unit test to verify that the suggested change produces the v expected result.

2021-04-05 18:36 UTC, erossignon commented on packages/node-opcua-variant/test/test_variant.js
> +        coerceVariantType(DataType.Boolean, true).should.eql(true);
Please add a test to check that "true"|"false" can be converted to true|false.

 coerceVariantType(DataType.Boolean, "true" /* a string here  */).should.eql(true);
 
coerceVariantType(DataType.Boolean, "false" /* a string here  */).should.eql(false);

2021-05-21 01:31 UTC, maneetgoyal commented on packages/node-opcua-variant/test/test_variant.js
> +        coerceVariantType(DataType.Boolean, true).should.eql(true);
On it 👍

2021-05-21 01:43 UTC, maneetgoyal commented on packages/node-opcua-variant/test/test_variant.js
> +        coerceVariantType(DataType.Boolean, true).should.eql(true);
Done, please check.

2021-08-20 09:03 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/node-opcua/node-opcua?pullRequest=929) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/node-opcua/node-opcua?pullRequest=929) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/node-opcua/node-opcua?pullRequest=929) it.</sub>

2021-10-04 04:28 UTC, closed without merging